apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ecr-regapp
  labels: 
     app: regapp

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: regapp

  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: ecr-regapp
        image:938096176081.dkr.ecr.us-east-1.amazonaws.com/dockerecr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1